### ISSUE TITLE
3.26.18

### ISSUE THREAD

**Issue by jraeglasgow** [jraeglasgow/Ali-1-1#1]
Weekly 1:1 😄

**Comment by alimarcozzi** [comment]
**Priority Accounts**
1. Honeywell
2. Prudential
3. Guardian Life
4. Deloitte
5. Marsh (including Oliver Wyman)

**What I would like to discuss**
- [ ] How to structure my day (dividing day to prospect on Sales Nav, create messaging, research my industry)
- [ ] Where to find industry specific content
- [ ] Best practices for researching multiple companies throughout the week
- [ ] Feedback on first 2.5 weeks as EBR

**Comment by jraeglasgow** [comment]
-Goals by next week:
1) Excel tracking doc for time expenditure and outputs: high level messaging 10 C level /day and 15 net new
2) test above one day 
3) Structure learnings times - using SE to do that 1-2 times per week
