### ISSUE TITLE
Sh!t I Need to know/ Where I Feel Lost

### ISSUE THREAD

**Issue by alimarcozzi** [jraeglasgow/Ali-1-1#3]
Things I would like to learn to better do my job as EBR:
- [x] When to use DiscoverOrg on an account
- [ ] Creating Subject lines
- [ ] Key words to search for in 10K reports, Google searches
- [ ] Key words to search for in SalesNav for prospects
- [ ] How to attack Tier 2 Prospecting Accounts (spray and pray)- Do I reach out to Director and above or Devs?
- [ ] How to prioritize contacts in an account to email in phases (to avoid mass emailing)- Should I separate by team/ department/ etc.
- [x] Where to find info for those more technical second convos
- [ ] How to send LinkedIn mail

**Comment by jraeglasgow** [comment]
**Two Week (in perp) Plan** 
AM Week One:
Build Assets:
Basic One-Off Templates
Cadences: for Director , Road Map, Cyber Security, Data Science 
PM Week ONE: Upload Contact based on tired accounts) 200 total by EOD Friday uploaded 

**Prioritizing Execution on Assets:**
**Goal One**: mention what GitHub has done for other companies we work with  - (internal sites), Issues , ESR/SE , anything from scoops or personal updates on top prospects 
**Goal Two**: Industry Trends - (google search) , top sites we can check for this stuff , internal slack sites 

Look at account - find trends > find content based on above (goal one, goal two ) > if no NEW content found > put them in basic cadence 

**Week 2 - executing on the above** 
AM - launch people you found in cadences from last week
PM - iterate on messaging and how you picked targets, then upload 20 no targets and edit account plans based on results for following week

**Comment by alimarcozzi** [comment]
**To do List:**
1. Reach out to Teaford/ Remy/ Parth/ Shane to get a list of top 5 places to look for this
1. Toast masters for public speaking

**Comment by alimarcozzi** [comment]
Just editing the comment- It's for finding more content 😄

**Comment by jraeglasgow** [comment]
Hey @alimarcozzi I wanted to checkin on the below when we have a chance and see how you were feeling on these things - 

> When to use DiscoverOrg on an account
  Creating Subject lines
  Key words to search for in 10K reports, Google searches
  Key words to search for in SalesNav for prospects
  How to attack Tier 2 Prospecting Accounts (spray and pray)- Do I reach out to Director and above or Devs?
  How to prioritize contacts in an account to email in phases (to avoid mass emailing)- Should I separate by team/ department/ etc.
  Where to find info for those more technical second convos
  How to send LinkedIn mail
