### ISSUE TITLE
May Planning - 4.26.18 1/1 

### ISSUE THREAD

**Issue by jraeglasgow** [jraeglasgow/Ali-1-1#5]
Hi @alimarcozzi, 

For our last one-on-one this month, I want to focus on a plan for May as it relates to your goals and plan of attack so far. Below is an outline of our monthly approach to success. I edited the outline to specific plans of attack you and I have recently discussed, connecting them to action items. There is also feedback on last month to take into May. 

Please let me know if you have any questions and I look forward to reviewing this together on Thursday. Note, the outline is all that needs to be done by the meeting, I wanted to give you a full week to finish your assets so you can focus on the end of the month as well! (Also note, the Master Issue Template should be ready by tomorrow, just wrapping up a few things.)

-Jess
___________________________________________________________________________________________________________
**May Plan** 

**What**: Need 7 Meetings to Hit - 11 to Hit 150%
**Who**: Top 5 Accounts/ ESR that will get you to 150% - This is our goal for you, what is your goal for yourself and when/how are you going to get there?
**When**: 
- Week 1 Activities 
- Week 2 Activities 
- Week 3 Activities
- Week 4 Activities 

**How**:
- Workflow: tools used, execution details: Reference this [Issue](https://github.com/jraeglasgow/Ali-1-1/issues/3) from working session to further look at flushing out activities 
- cadences used -

**Action Items**: 
- [ ] **Who**: Pick Top 5 Accounts and Finish Master Issue and Tier Sheet for Each by EOD Monday, April 30th 
- [ ] **When**: Map which activities to weeks to create plan to reach goal of 11 meetings 
- [ ] **How**: outline ( high level example of how you are going to execute your plan for May) 

**April Feedback** 
- good job proactively looking for sources of truth and assets
- not everything has to be perfect - done is better than perfect (Wheeler) 
- the last two weeks in the month (specifically since you came in Monday morning 4.16.18, you have been more focused and productive in both numbers and appearance - keep it up  
-when making your assets, try and see what areas you need to understand more of to get a complete view of the account opportunity and be proactive in asking for support in filling these gaps with ESR/RD/Leadership 

**Assets**: 

- [SalesDev Account Tier/Mapping Template
](https://docs.google.com/spreadsheets/d/1W2FbnQrdPdLaCUsVQPJQq7YcUmN4IgAlRPA2xkqnlI4/edit#gid=1762991169)
- Master Issue Template 
## Company X

**SFDC** (link to Salesforce search for 'Company X')
**LinkedIn** 
**DiscoverOrg**
**Master spreadsheet**
**HQ:**  

#### VCS info
- **Current VCS:** 
- **Past GitHub trials:** 
- **Noticeable GitHub.com presence?** 

#### Context
- **Any similar customers?** (look for trends, key words, what's driving change?)
- **Any known tech initiatives?** (could be based on past conversations and/or on current info in the news)
- **Any known BUs? Which ones are we approaching?**
- **Key stakeholders:** (could be based on past conversations and/or on current info in the news)

#### 1st campaign: [who's being targetted]  
- **Why them?**
- **Target contacts:** (individuals, personas, or a specific BU)
  - ...

### Links to related Issues, Halp threads, SFDC notes
- ...

**Comment by alimarcozzi** [comment]
**May Plan** 

**What**: Need 7 Meetings to Hit - 11 to Hit 150%
**Who**: Top 5 Accounts/ ESR that will get you to 150%
**BHAG**: Hit 150% each month for 6 months

**When**: 
- Week 1 Activities 
AM Week One:
-Build asset: build a ♥️ GitHub campaign/ templates for people who have GitHub in their profile or are an A+ contact
-Launch 20 new Director cadences (Mon), 20 new Roadmap cadences (Tues), 20 new Manager cadences (Wed), 20 new ♥️ GitHub cadences (Thurs)
PM Week ONE: 
-Call block
-Upload Contacts (based on tired accounts) 200 total by EOD Friday uploaded
-40% Director+ for RoadMap campaign, 30% Director/ Manager for Director/ DevOps campaign, 30% ♥️ GitHub campaign

- Week 2 Activities 
AM Week TWO:
-Build asset: Build out RoadMap campaign to include value-added content
-Launch 20 new Director cadences (Mon), 20 new Roadmap cadences (Tues), 20 new Manager cadences (Wed), 20 new ♥️ GitHub cadences (Thurs)
PM Week TWO: 
-Call block
-Upload Contacts (based on tired accounts) 200 total by EOD Friday uploaded
-40% Director+ for RoadMap campaign, 30% Director/ Manager for Director/ DevOps campaign, 30% ♥️ GitHub campaign

- Week 3 Activities
AM Week THREE:
-Build asset: Cold calling practice (role playing, extra call blocks)
-Launch 20 new Director cadences (Mon), 20 new Roadmap cadences (Tues), 20 new Manager cadences (Wed), 20 new ♥️ GitHub cadences (Thurs)
PM Week THREE: 
-Call block
-Upload Contacts (based on tired accounts) 200 total by EOD Friday uploaded
-40% Director+ for RoadMap campaign, 30% Director/ Manager for Director/ DevOps campaign, 30% ♥️ GitHub campaign

- Week 4 Activities 
AM Week FOUR:
-Build asset: Build and Present the Decker Training Information
-Launch 20 new Director cadences (Mon), 20 new Roadmap cadences (Tues), 20 new Manager cadences (Wed), 20 new ♥️ GitHub cadences (Thurs)
PM Week FOUR: 
-Call block
-Upload Contacts (based on tired accounts) 200 total by EOD Friday uploaded
-40% Director+ for RoadMap campaign, 30% Director/ Manager for Director/ DevOps campaign, 30% ♥️ GitHub campaign

**How**:
- Workflow: launch 20 new campaigns each day
- cadences used - RoadMap, Director Campaign, Jenkins Days Boston F/U, ♥️ GitHub 
- **assets** 
-use Data Science, FinTech, and Security templates 

**Action Items**: 
- [ ] **Who**: Pick Top 5 Accounts and Finish Master Issue and Tier Sheet for Each by EOD Monday, April 30th 
- [ ] **When**: Map which activities to weeks to create plan to reach goal of 11 meetings 
- [ ] **How**: outline ( high level example of how you are going to execute your plan for May)

**Comment by jraeglasgow** [comment]
@alimarcozzi a good exercise ( no more than a few minutes) would be to take a look at the above and just see how much was different in your execution if anything. We tend to be great at making plans but reflecting on how they were executed is often where the real learnings happen.
